### PR TITLE
fixes #10

### LINKED ISSUE #10: Disabling migration backups breaks template
When running Craft with these general settings:

```
    'backupDbOnUpdate' => false,
    'restoreDbOnUpdateFailure' => false,
```

The migration breaks with this error:

screenshot 2018-05-09 14 36 13

This is due to an error here:

https://github.com/Firstborn/Craft-Migration-Manager/blob/master/src/controllers/RunController.php#L59

There is no else case for ```if ($backup) {```

Suggested fix:

```
if ($backup) {
    try {
        $db->backup();
        return $this->asJson(array(
            'alive' => true,
            'nextStatus' => Craft::t('migrationmanager', 'Running migrations ...'),
            'nextAction' => 'migrationmanager/run/migrations',
            'data' => $data,
        ));
    } catch (\Throwable $e) {
        Craft::$app->disableMaintenanceMode();
        return $this->asJson(array(
            'alive' => true,
            'errorDetails' => $e->getMessage(),
            'nextStatus' => Craft::t('migrationmanager', 'An error was encountered. Rolling back ...'),
            'nextAction' => 'migrationmanager/run/rollback',
            'data' => $data,
        ));
    }
} else {
    return $this->asJson(array(
        'alive' => true,
        'nextStatus' => Craft::t('migrationmanager', 'Running migrations ...'),
        'nextAction' => 'migrationmanager/run/migrations',
        'data' => $data,
    ));
}
```

### PR DESCRIPTION
**Pull request by gregorskii**
provides fallback when disable backups is true

### CODE REVIEW

**Comment by gregorskii** [comment]
Pardon me asking, as I do not know this info, but after this PR when does this make it to composer require installs?

**Comment by fb-derrick-grigg** [comment]
You should see it now, release 3.0.8

**Comment by gregorskii** [comment]
Thanks :)

**Comment by gregorskii** [comment]
When does it hit composer/packagist? It fails to resolve there.

**Comment by fb-derrick-grigg** [comment]
It doesn't. The repo should be pointed at github in your composer file. It should hit the repo directly.

**Comment by gregorskii** [comment]
Ah yes, confirmed. Before it was reading from Composer directly, added the VCS repo.

Thanks

**Pull request merged**
